{
 "title": "Sample Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ss", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Virtual Users",
   "type": "stat",
   "description": "Max Virtual Users",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "k6_vus_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "description": "Max Virtual Users",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_reqs_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time Max Percentile 99",
   "type": "stat",
   "description": "Max Virtual Users",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(k6_http_req_duration_p99)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "% Errors",
   "type": "stat",
   "description": "Max Virtual Users",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(k6_http_req_failed_rate)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max CPU Usage Sample",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_cpu_usage_seconds_total{name=\"dockertools-sampleloadapp-1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max CPU Usage SQL Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_cpu_usage_seconds_total{name=\"dockertools-sqlserver-1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Memory Usage Sample",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name=\"dockertools-sampleloadapp-1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Memory Usage SQL Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name=\"dockertools-sqlserver-1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "avg(k6_vus)", "legendFormat": "__auto" },
    {
     "expr": "sum(rate(k6_http_reqs_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "irate(container_cpu_system_seconds_total{name=\"dockertools-sampleloadapp-1\"}[120s])* 100",
     "legendFormat": "Sample_App"
    },
    {
     "expr": "irate(container_cpu_system_seconds_total{name=\"dockertools-sqlserver-1\"}[120s])*100",
     "legendFormat": "Sample_SQL"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "avg(k6_http_req_duration_p99)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"dockertools-sampleloadapp-1\"}",
     "legendFormat": "Sample_App"
    },
    {
     "expr": "container_memory_usage_bytes{name=\"dockertools-sqlserver-1\"}",
     "legendFormat": "Sample_SQL"
    }
   ]
  },
  {
   "title": "Request",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg by(group, method, name) (k6_http_req_duration_p99)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "avg by(group) (k6_group_duration_p99)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}